version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet build -c Release ./mEMDA-api-dotnet-core/mEMDA-api-dotnet-core/mEMDA-api-dotnet-core.csproj
