branch-defaults:
  circleci-project-setup:
    environment: ViocareWebApp
global:
  application_name: ViocareWebApp-test
  default_ec2_keyname: e-deitkmkhm3
  default_platform: .NET Core running on 64bit Amazon Linux 2/2.2.9
  default_region: us-east-1
  sc: git
