version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Deploying"
          command: eb deploy ViocareWebApp-test
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
