version: 2.1

dependencies:
    pre:
      - pip install awsebcli
deployment:
  develop:
    branch: develop
    commands:
      - eb use ViocareWebApp-test --viocare-VioscreenAPI default
      - eb deploy --viocare-VioscreenAPI default
