version: 2.1

orbs:  
  build-tools: circleci/build-tools@x.y.z

jobs:
  build:
    description: Build application with Release configuration
    executor:
      machine:
        machine: true
    steps:
      - checkout
      - run: npm install
      - run: sudo pip install awsebcli --upgrade
      - run: echo AKIAXNVGZ2DF5UGNQBVT
      - run:
          name: "Deploying"
          command: eb deploy ViocareWebApp-test
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
