version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\ViocareWebApp
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Debug -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp3.1\win10-x64\publish\ViocareWebApp.exe 
      - store_artifacts:
          path: .\bin\Release\netcoreapp3.1\win10-x64\publish\ViocareWebApp.exe
          
workflows:
  hello-world:
    jobs:
      - build
